import "server-only"

import "./globals.css"
import SupabaseListener from "@/supabase/components/supabase-listener"
import SupabaseProvider from "@/supabase/components/supabase-provider"
import { createClient } from "@/supabase/utils/server"
import { Inter } from "next/font/google"
// do not cache this layout
export const revalidate = 0

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const inter = Inter({ subsets: ["latin"] })

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createClient()

  const {
    data: { session },
  } = await supabase.auth.getSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <SupabaseListener serverAccessToken={session?.access_token} />
          {children}
        </SupabaseProvider>
      </body>
    </html>
  )
}
